### ISSUE TITLE
Bug: Исчезновения баллона воздуха, при откреплении его от РИГА.

### ISSUE THREAD

**Issue by Valensi1234** [ss220-space/NebulaHestia#67]
### Ckey

Valensi

### Описание бага

Исчезновения баллона воздуха, при откреплении его от РИГА.

### Шаги воспроизведения

1.прикрепить баллон к РИГу
2.снять баллон с рига с помощью отвертки 
Ожидаемое поведение

### Ожидаемое поведение

баллон выпадет на пол или появится в руке.

### Операционная система

Windows 10

### Версия клиента

514.1575

### Название сервера

WL

### Примерное время и дата

16:00~17:00 27.12.21

**Comment by Valensi1234** [comment]
Исчезновения баллона воздуха, при откреплении его от РИГА.

**Comment by Ge4ok** [comment]
Добавлю, что так со всеми вещами. Только что открепил магбутсы - они тоже пропали
